
    + CategoryInfo          : NotSpecified: ((node:2252) Exp...nge at any time:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
-- Import jobs from CSV
-- This script uses INSERT ... ON CONFLICT to update existing records
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE',
  NULL,
  NULL,
  'FT',
  0,
  42,
  'Curran Advani',
  '2025-12-05'::timestamp,
  '1ΓÇ¥ SCH 40 PIPE',
  true,
  true,
  NULL,
  '00004DB010',
  'Fab''d',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'FT',
  0,
  42,
  'Current User',
  '2025-12-03'::timestamp,
  '1ΓÇ¥ SCH 40 PIPE',
  true,
  true,
  NULL,
  '00004DB010',
  'Shop',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'FT',
  0,
  21,
  'Current User',
  '2025-12-03'::timestamp,
  '1-1/4ΓÇ¥ SCH 40 PIPE',
  true,
  NULL,
  NULL,
  '00004DB012',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  12,
  'Current User',
  '2025-12-03'::timestamp,
  '1ELLDI',
  true,
  NULL,
  NULL,
  '1111000010',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  6,
  'Current User',
  '2025-12-03'::timestamp,
  '1-1/4 ELL DI',
  true,
  NULL,
  NULL,
  '1111000012',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  3,
  'Current User',
  '2025-12-03'::timestamp,
  '1TEEDI',
  true,
  NULL,
  NULL,
  '1113000010',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'Current User',
  '2025-12-03'::timestamp,
  '1X1X1-1/4 TEE DI',
  true,
  NULL,
  NULL,
  '1113101012',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  3,
  'Current User',
  '2025-12-03'::timestamp,
  '1-1/4 X 1-1/4 X 1 TEE DI',
  true,
  NULL,
  NULL,
  '1113121210',
  'Fab''d',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'Current User',
  '2025-12-02'::timestamp,
  '1-1/4" COUPLING DI',
  true,
  true,
  NULL,
  '1115000012',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  2,
  'Current User',
  '2025-12-03'::timestamp,
  '4 FT QUICK DROP 1/2',
  true,
  NULL,
  NULL,
  '15QUICDRP4',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  5,
  'Current User',
  '2025-12-03'::timestamp,
  'VK3021 K5.6 1/2 QR CH Pend 200 W/ ESCUTCHEON',
  true,
  NULL,
  NULL,
  '5B30210C6P',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  6,
  'Current User',
  '2025-12-03'::timestamp,
  '1 HANGER RING',
  true,
  NULL,
  NULL,
  '6000000010',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  4,
  'Current User',
  '2025-12-03'::timestamp,
  '1-1/4 HANGER RING',
  true,
  NULL,
  NULL,
  '6000000012',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'EA',
  0,
  12,
  'Current User',
  '2025-12-03'::timestamp,
  '3/8 CONCRETE SCREW ANCHOR HILTI',
  true,
  NULL,
  NULL,
  '6024000038',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1379',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  '1896',
  'ZOETIS B300 PHASE 2 SE FREEZER FARM',
  NULL,
  NULL,
  'FT',
  0,
  48,
  'Current User',
  '2025-12-03'::timestamp,
  '3/8 A.T. ROD ZINC',
  true,
  NULL,
  NULL,
  '6027003000',
  'Loose',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '45019401',
  'Meadow Stone - Bldg 614',
  NULL,
  NULL,
  'Meadow Stone - Bldg 614',
  NULL,
  NULL,
  NULL,
  0,
  2,
  NULL,
  NULL,
  'STEEL BODY, KEYED ALIKE, BREAKAWAY LOCK',
  NULL,
  NULL,
  NULL,
  'ML500KABRK',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '45019401',
  'Meadow Stone - Bldg 614',
  NULL,
  NULL,
  'Meadow Stone - Bldg 614',
  NULL,
  NULL,
  NULL,
  0,
  0,
  NULL,
  NULL,
  '4VKATOOK3.ORESPDCH155',
  NULL,
  NULL,
  NULL,
  '17492FB',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '24-1361-2946',
  '301 market',
  NULL,
  NULL,
  '301 market',
  NULL,
  NULL,
  NULL,
  0,
  2,
  NULL,
  NULL,
  'Grooved 2" tee',
  NULL,
  NULL,
  NULL,
  '0',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  988,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1-1/2" SCH 10 PIPE',
  NULL,
  NULL,
  NULL,
  '00001DB015',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  11,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '2" SCH 10 PIPE',
  NULL,
  NULL,
  NULL,
  '00001DB020',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  232,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '3ΓÇ¥ SCH 10 PIPE',
  NULL,
  NULL,
  NULL,
  '00001DB030',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  40,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '4" SCH 10 PIPE',
  NULL,
  NULL,
  NULL,
  '00001DB040',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  214,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1ΓÇ¥ SCH 40 PIPE',
  NULL,
  NULL,
  NULL,
  '00004DB010',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1 X 1/2 ELL MI GALV',
  true,
  true,
  NULL,
  '1201001005',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '2" 45 ELL MI GALV',
  true,
  true,
  NULL,
  '1202000020',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1X 1/2 TEE DI',
  true,
  true,
  NULL,
  '1113101005',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1/2 REDUCER DI',
  true,
  true,
  NULL,
  '1115001005',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  'CAP DI',
  true,
  true,
  NULL,
  '1117C00010',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  'PLUG DI',
  true,
  true,
  NULL,
  '1117P00010',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '6" GxF nipple adapter galv',
  true,
  false,
  NULL,
  '14F6FA3060',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  17,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1/2 X 1/2 WELD POL',
  NULL,
  NULL,
  NULL,
  '14WO0P01505',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  20,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1 WELD POL',
  NULL,
  NULL,
  NULL,
  '14WO0P01510',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  24,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  'WELD GRV POL',
  NULL,
  NULL,
  NULL,
  '14WO0V03015',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  4,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '2 VIC GRVD SHORT RADIUS ELLY',
  NULL,
  NULL,
  NULL,
  '26F1000020',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  34,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1 1/2" VIC Long Rad Ell Vv',
  NULL,
  NULL,
  NULL,
  '2601000015',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  1,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1 1/2" VIC Long Rad Tee',
  true,
  true,
  NULL,
  '2603000015',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  2,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '4 X3 GEM GRVD CON RED',
  NULL,
  NULL,
  NULL,
  '2E05C04030',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;
INSERT INTO jobs (
  job_number,
  job_name,
  contract_number,
  list_number,
  area,
  location_ship_to,
  stocklist_delivery_ship_date,
  unit_of_measurement,
  pulled,
  quantity_needed,
  pulled_by,
  pulled_date,
  description,
  ordered,
  received_from_order,
  delivered,
  part_number,
  type,
  part_type,
  "createdAt",
  "updatedAt"
  '25-1120',
  'Fox Kia OFFICE',
  NULL,
  '202',
  'Fox Kia OFFICE',
  NULL,
  NULL,
  'EA',
  0,
  5,
  'ANDREW NORRIS',
  '2025-12-03'::timestamp,
  '1 x 0-6" IGS NIPPLE Thread by Groove',
  NULL,
  NULL,
  NULL,
  '3410001060',
  NULL,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
ON CONFLICT (job_number, part_number) 
DO UPDATE SET
  job_name = EXCLUDED.job_name,
  contract_number = EXCLUDED.contract_number,
  list_number = EXCLUDED.list_number,
  area = EXCLUDED.area,
  location_ship_to = EXCLUDED.location_ship_to,
  stocklist_delivery_ship_date = EXCLUDED.stocklist_delivery_ship_date,
  unit_of_measurement = EXCLUDED.unit_of_measurement,
  pulled = EXCLUDED.pulled,
  quantity_needed = EXCLUDED.quantity_needed,
  pulled_by = EXCLUDED.pulled_by,
  pulled_date = EXCLUDED.pulled_date,
  description = EXCLUDED.description,
  ordered = EXCLUDED.ordered,
  received_from_order = EXCLUDED.received_from_order,
  delivered = EXCLUDED.delivered,
  type = EXCLUDED.type,
  part_type = EXCLUDED.part_type,
  "updatedAt" = CURRENT_TIMESTAMP;


